name: CI
run-name: ${{ github.actor }} is running CI
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: NPM install
        run: npm install
      - name: Svelte check
        run: npm run check
      - name: format check
        run: npm run format:check
      - name: eslint check
        run: npm run lint
      - name: Run test
        run: npm run test